#!/usr/bin/env python
"""pull all pushed changes

on each push for this repo do pull

From Example for Python GitHub Webhooks

"""


import sys
import json
from git.cmd import Git

with open(sys.argv[1], 'r') as jsf:
    PAYLOAD = json.loads(jsf.read())

if PAYLOAD['repository']['name'] == '4k' and PAYLOAD['refs'] == 'refs/heads/stable':
    G = Git('/home/obezpalko/src/4k')
    G.pull()
