#!/usr/bin/env python

# Python Example for Python GitHub Webhooks
# File: push-myrepo-master

import sys
import json
from git.cmd import Git

with open(sys.argv[1], 'r') as jsf:
    PAYLOAD = json.loads(jsf.read())

if PAYLOAD['repository']['name'] == '4k' and PAYLOAD['refs'] == 'refs/heads/stable':
    G = Git('/home/obezpalko/src/4k')
    G.pull()
